# **Step 1: Creating Token**

Loading the dataset that we need to work on (it is a short story dataset by edhit wharton)

In [18]:
with open("the-verdict.txt","r",encoding="utf-8") as f:
    raw_text=f.read()
print("Total number of character:",len(raw_text))
print(raw_text[:99])

Total number of character: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [19]:
import re
text="hello world. this is a test"
result= re.split(r'(\s)',text) #rsplits from all the white spaces
print(result)

['hello', ' ', 'world.', ' ', 'this', ' ', 'is', ' ', 'a', ' ', 'test']


In [20]:
result=re.split(r'([,.]|\s)',text)
print(result)

['hello', ' ', 'world', '.', '', ' ', 'this', ' ', 'is', ' ', 'a', ' ', 'test']


In [21]:
result=[item for item in result if item.strip()] #remove white space in the list
print(result)

['hello', 'world', '.', 'this', 'is', 'a', 'test']


in tokenization to keep or to not keep spaces it all depends on the problem statemenet that we are dealing with that means some problems that need exactly same structure as the input require white spaces, for example a python code is space sensitive therefore in that case we need not to remove white spaces

**Appplying this tokenizing knowledge on our dataset**

In [22]:
token= re.split(r'([,.;!_?@$%^&*()+=\'\#]|--|\s)', raw_text)
token=[item for item in token if item.strip()]
print(token[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [23]:
print(len(token))

4585


# **Step 2: Creating token IDs**

tokenized text -> vocabulary (map all in alphabetical order then give unique ID)

In [24]:
words= sorted(set(token))
vocab_size= len(words)
print(vocab_size)

1173


thus now we have 1191 tokens

In [25]:
vocab={token:integer for integer, token in enumerate(words)}

In [26]:
for i,item in enumerate(vocab.items()):
    print(item)
    if i>=50:
        break

('!', 0)
('"', 1)
('"Ah', 2)
('"Be', 3)
('"Begin', 4)
('"By', 5)
('"Come', 6)
('"Destroyed', 7)
('"Don', 8)
('"Gisburns"', 9)
('"Grindles', 10)
('"Hang', 11)
('"Has', 12)
('"How', 13)
('"I', 14)
('"If', 15)
('"It', 16)
('"Jack', 17)
('"Money', 18)
('"Moon-dancers"', 19)
('"Mr', 20)
('"Mrs', 21)
('"My', 22)
('"Never', 23)
('"Of', 24)
('"Oh', 25)
('"Once', 26)
('"Only', 27)
('"Or', 28)
('"That', 29)
('"The', 30)
('"Then', 31)
('"There', 32)
('"There:', 33)
('"This', 34)
('"We', 35)
('"Well', 36)
('"What', 37)
('"When', 38)
('"Why', 39)
('"Yes', 40)
('"You', 41)
('"but', 42)
('"deadening', 43)
('"dragged', 44)
('"effects"', 45)
('"interesting":', 46)
('"lift', 47)
('"obituary"', 48)
('"strongest', 49)
('"strongly"', 50)


**creating tokenizer class**

In [27]:
class tokenize:
    def __init__(self,vocab):
        self.str_to_int=vocab
        self.int_to_str={i:s for s,i in vocab.items()}
    def encode(self,text):
        token= re.split(r'([,.;!_@$%^&*()+=\'\#]|--|\s)',text)
        token=[item.strip() for item in token if item.strip()]
        ids=[self.str_to_int[s] for s in token]
        return ids
    def decode(self,ids):
        #recreating the text from tokens
        text=" ".join([self.int_to_str[i] for i in ids])
        text=re.sub(r'\s+([,.?!"()\'])',r'\1',text)
        return text

In [28]:
tokens=tokenize(vocab)
text= "I HAD always thought Jack Gisburn rather a cheap genius--though a good."
ids=tokens.encode(text)
txt=tokens.decode(ids)
print(ids)
print(txt)

[93, 87, 182, 1043, 97, 82, 858, 147, 289, 518, 56, 1042, 147, 533, 57]
I HAD always thought Jack Gisburn rather a cheap genius -- though a good.


**what if encounter a awork out of our vocaabulary?**
we use <|unk|> & <|endoftext|> tokens in the vocabulary to tckle this situation

In [29]:
alltoken=sorted(list(token))
alltoken.extend(["<|endoftext|>","<|unk|>"])
vocab2={token:integer for integer,token in enumerate(alltoken)}

In [30]:
len(vocab2.items())

1175

In [31]:
class tokenize:
    def __init__(self,cab):
        self.str_to_int=cab
        self.int_to_str={i:s for s,i in cab.items()}
    def encode(self,text):
        token= re.split(r'([,.;!_@$%^&*()+=\'\#]|--|\s)',text)
        token=[item.strip() for item in token if item.strip()]
        token=[item if item in self.str_to_int
            else "<|unk|>" for item in token]
        ids=[self.str_to_int[s] for s in token]
        return ids
    def decode(self,ids):
        #recreating the text from tokens
        text=" ".join([self.int_to_str[i] for i in ids])
        text=re.sub(r'\s+([,.?!"()\'])',r'\1',text)
        return text

In [32]:
tokenize=tokenize(vocab2)
t1="Hello, do you like tea?"
t2="In the sunlit terraces of the palace."
text="<|endoftext|>".join((t1,t2))
print(text)

Hello, do you like tea?<|endoftext|>In the sunlit terraces of the palace.


In [33]:
tokenize.decode(tokenize.encode(text))

'<|unk|>, do you like <|unk|> the sunlit terraces of the <|unk|>.'

# "BYTE_PAIR_Encoding"

In [34]:
!pip install tiktoken


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [35]:
import tiktoken



Creating an instance of tokenizer class from tiktoken, it works just like our version of tokenizer

In [36]:
tokenizer=tiktoken.get_encoding("gpt2")

In [37]:
text=("Hello, do you like tea?<|endoftext|>In the sunlit terraces of the palace.")
integer=tokenizer.encode(text,allowed_special={'<|endoftext|>'})
print(integer)

[15496, 11, 466, 345, 588, 8887, 30, 50256, 818, 262, 4252, 18250, 8812, 2114, 286, 262, 20562, 13]


In [38]:
string=tokenizer.decode(integer)
print(string)

Hello, do you like tea?<|endoftext|>In the sunlit terraces of the palace.


_we can clearly see here, it handles both <|unk|> and <|endoftext|> tokens easily, as it is using BPE at root level thus shows no error and runs smoothly, moreover it is also trained on larger dataset_

In [39]:
enc_text=tokenizer.encode(raw_text)
print(len(enc_text))

5145


# **INPUT-TARGET PAIRS**

In [40]:
context_size = 4 #length of the input
enc_sample=enc_text[:50]
#The context_size of 4 means that the model is trained to look at a sequence of 4 words (or tokens) 
#to predict the next word in the sequence. 
#The input x is the first 4 tokens [1, 2, 3, 4], and the target y is the next 4 tokens [2, 3, 4, 5]
x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]
print(f"x: {x}")
print(f"y:      {y}")

x: [40, 367, 2885, 1464]
y:      [367, 2885, 1464, 1807]


In [41]:
for i in range(1,context_size+1):
    context=enc_sample[:i]
    desired=enc_sample[i]
    print(tokenizer.decode(context),"------->",tokenizer.decode([desired]))

I ------->  H
I H -------> AD
I HAD ------->  always
I HAD always ------->  thought


the above created is a very simple version for input-target pairing, we will use Pytorch Tensors for actual implementation.
Tendors are nothing but 2D matrices which store some data
following is the implementation for the same:

# Dataset & Data-loader 

we will use 2 2D arrays, one with actual input and one with one place shifted input and all will be row wise related

Step 1: Tokenize the entire text

Step 2: Use a sliding window to chunk the book into overlapping sequences of max_length

Step 3: Return the total number of rows in the dataset

Step 4: Return a single row from the dataset

Below is the implementation for dataset

In [42]:
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
    #txt is sample text, tokenizer is the BPE class , Max_length refers to context size,tride is how long to jump
    def __init__(self,txt,tokenizer, max_length,stride):
        self.input_ids=[]
        self.target_ids=[]

        token_ids=tokenizer.encode(txt,allowed_special={"<|endoftext|>"})

        for i in range(0, len(token_ids)-max_length,stride):
            input_chunk=token_ids[i:i+max_length]
            target_chunk=token_ids[i+1:i+max_length+1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))
    
    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self,idx):
        return self.input_ids[idx],self.target_ids[idx]

DataLoader

Step 1: Initialize the tokenizer

Step 2: Create dataset

Step 3: drop_last=True drops the last batch if it is shorter than the specified batch_size to prevent loss spikes during training

Step 4: The number of CPU processes to use for preprocessing

In [43]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,num_workers=0):
    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")
    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )
    return dataloader #the input output pairs

Testing our dataset and adatloader piplene

In [44]:
import torch
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [45]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [46]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


# CREATE TOKEN EMBEDDINGS

In [47]:
import torch
input_ids = torch.tensor([2, 3, 5, 1])

In [48]:
vocabsize = 6
layer = 3

torch.manual_seed(123)
embedding = torch.nn.Embedding(vocabsize, layer)

In [49]:
print(embedding.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


these are the randomly generated embedding weights, which will be further optimised, but thing to notic here is that we have a tensor of 3 features and vocabsize of 6 thus getting weight for each token wrt to the vector embedding features

In [50]:
print(embedding(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


# **Postional Embeddings (emebed relative to position)**

Initiate the emebedding layer

In [51]:
vocabsize=50257
output=256

embedding_layer=torch.nn.Embedding(vocabsize,output)

Create dataloader (that is data sampling with sliding window)

In [52]:
max_len=4
dataloader=create_dataloader_v1(raw_text,batch_size=8,max_length=max_len,stride=max_len,shuffle=False)
data_iter=iter(dataloader)
inputs,targets=next(data_iter)

SIMPLE ANALOGY

dataloader = tokens of words

dataloder-> vector embedding 

vector embedding = each token with the vector dimension

_FOR POSITIONAL EMBEDDING_

size= context_length*vector_dimensions

because it will only embed the position for the given context size, not more not less

In [56]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [58]:
token_embeddings = embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [66]:
context_length = max_len
pos_embedding_layer = torch.nn.Embedding(context_length, output)

In [67]:
pos_embeddings = pos_embedding_layer(torch.arange(max_len))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [68]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])


In [69]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
